---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for Batch
Parameters:
  SystemName:
    Description: System Name.
    Type: String
    Default: iobatch
  EnvType:
    Description: Environment Type.
    Type: String
    Default: prd
  IamStackName:
    Description: IAM Stack Name.
    Type: String
    Default: iobatch-prd-iam
  VpcStackName:
    Description: Vpc Stack Name.
    Type: String
    Default: iobatch-prd-vpc
Resources:
  # EC2 Security Group
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${SystemName}-${EnvType}-ec2-security-group
      GroupDescription: !Sub ${SystemName}-${EnvType}-ec2-security-group
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-Vpc
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-ec2-security-group
  # EC2 Launch Template (AL2)
  Ec2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${SystemName}-${EnvType}-ec2-launch-template
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 2000
              VolumeType: gp3
              Iops: 1600
              Throughput: 1000
              Encrypted: true
              DeleteOnTermination: true
        InstanceInitiatedShutdownBehavior: terminate
  # Batch Compute Environments (Spot)
  BatchComputeEnvironmentFargateSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-fargate-spot
      ComputeResources:
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: FARGATE_SPOT
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2GravitonSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-ec2-graviton-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateName: !Sub ${SystemName}-${EnvType}-ec2-launch-template
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${IamStackName}-BatchEc2InstanceProfile
        SpotIamFleetRole: !Sub ${IamStackName}-BatchSpotFleetRole
        InstanceTypes:
          - c6g
          - m6g
          - r6g
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2IntelSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-ec2-intel-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateName: !Sub ${SystemName}-${EnvType}-ec2-launch-template
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${IamStackName}-BatchEc2InstanceProfile
        SpotIamFleetRole: !Sub ${IamStackName}-BatchSpotFleetRole
        InstanceTypes:
          - m6i
          - c5    # => c6i
          - r5
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2NvidiaSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-ec2-nvidia-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateName: !Sub ${SystemName}-${EnvType}-ec2-launch-template
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
        Ec2Configuration:
          - ImageType: ECS_AL2_NVIDIA
        InstanceRole:
          Fn::ImportValue: !Sub ${IamStackName}-BatchEc2InstanceProfile
        SpotIamFleetRole: !Sub ${IamStackName}-BatchSpotFleetRole
        InstanceTypes:
          - p4d
          - g4dn.xlarge
          - g4dn.2xlarge
          - g4dn.4xlarge
          - g4dn.8xlarge
          - g4dn.12xlarge
          - g4dn.16xlarge
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  # Batch Job Queues (Spot)
  BatchJobQueueFargateSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentFargateSpot
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-fargate-spot
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2GravitonSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2GravitonSpot
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-ec2-graviton-spot
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2IntelSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2IntelSpot
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-ec2-intel-spot
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2NvidiaSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2NvidiaSpot
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-ec2-nvidia-spot
      Priority: 1
      State: ENABLED
  # Batch Compute Environments (OnDemand)
  BatchComputeEnvironmentFargateOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-fargate-ondemand
      ComputeResources:
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: FARGATE
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2GravitonOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-ec2-graviton-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT_PROGRESSIVE
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateName: !Sub ${SystemName}-${EnvType}-ec2-launch-template
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${IamStackName}-BatchEc2InstanceProfile
        InstanceTypes:
          - c6g
          - m6g
          - r6g
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2IntelOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-ec2-intel-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT_PROGRESSIVE
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateName: !Sub ${SystemName}-${EnvType}-ec2-launch-template
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${IamStackName}-BatchEc2InstanceProfile
        InstanceTypes:
          - m6i
          - c5    # => c6i
          - r5
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2NvidiaOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${SystemName}-${EnvType}-batch-compute-environment-ec2-nvidia-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT_PROGRESSIVE
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - !Ref Ec2SecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateName: !Sub ${SystemName}-${EnvType}-ec2-launch-template
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet2
          - Fn::ImportValue: !Sub ${VpcStackName}-ApplicationSubnet3
        Ec2Configuration:
          - ImageType: ECS_AL2_NVIDIA
        InstanceRole:
          Fn::ImportValue: !Sub ${IamStackName}-BatchEc2InstanceProfile
        InstanceTypes:
          - p4d
          - g4dn.xlarge
          - g4dn.2xlarge
          - g4dn.4xlarge
          - g4dn.8xlarge
          - g4dn.12xlarge
          - g4dn.16xlarge
      ServiceRole:
        Fn::ImportValue: !Sub ${IamStackName}-BatchServiceRole
      State: ENABLED
  # Batch Job Queues (OnDemand)
  BatchJobQueueFargateOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentFargateOnDemand
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-fargate-ondemand
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2GravitonOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2GravitonOnDemand
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-ec2-graviton-ondemand
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2IntelOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2IntelOnDemand
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-ec2-intel-ondemand
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2NvidiaOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2NvidiaOnDemand
      JobQueueName: !Sub ${SystemName}-${EnvType}-batch-job-queue-ec2-nvidia-ondemand
      Priority: 1
      State: ENABLED
Outputs:
  Ec2SecurityGroup:
    Value: !Ref Ec2SecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-Ec2SecurityGroup
  Ec2LaunchTemplate:
    Value: !Ref Ec2LaunchTemplate
    Export:
      Name: !Sub ${AWS::StackName}-Ec2LaunchTemplate
  BatchComputeEnvironmentFargateSpot:
    Value: !Ref BatchComputeEnvironmentFargateSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentFargateSpot
  BatchComputeEnvironmentEc2GravitonSpot:
    Value: !Ref BatchComputeEnvironmentEc2GravitonSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentEc2GravitonSpot
  BatchComputeEnvironmentEc2IntelSpot:
    Value: !Ref BatchComputeEnvironmentEc2IntelSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentEc2IntelSpot
  BatchComputeEnvironmentEc2NvidiaSpot:
    Value: !Ref BatchComputeEnvironmentEc2NvidiaSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentEc2NvidiaSpot
  BatchJobQueueFargateSpot:
    Value: !Ref BatchJobQueueFargateSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueFargateSpot
  BatchJobQueueEc2GravitonSpot:
    Value: !Ref BatchJobQueueEc2GravitonSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueEc2GravitonSpot
  BatchJobQueueEc2IntelSpot:
    Value: !Ref BatchJobQueueEc2IntelSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueEc2IntelSpot
  BatchJobQueueEc2NvidiaSpot:
    Value: !Ref BatchJobQueueEc2NvidiaSpot
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueEc2NvidiaSpot
  BatchComputeEnvironmentFargateOnDemand:
    Value: !Ref BatchComputeEnvironmentFargateOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentFargateOnDemand
  BatchComputeEnvironmentEc2GravitonOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2GravitonOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentEc2GravitonOnDemand
  BatchComputeEnvironmentEc2IntelOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2IntelOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentEc2IntelOnDemand
  BatchComputeEnvironmentEc2NvidiaOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2NvidiaOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchComputeEnvironmentEc2NvidiaOnDemand
  BatchJobQueueFargateOnDemand:
    Value: !Ref BatchJobQueueFargateOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueFargateOnDemand
  BatchJobQueueEc2GravitonOnDemand:
    Value: !Ref BatchJobQueueEc2GravitonOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueEc2GravitonOnDemand
  BatchJobQueueEc2IntelOnDemand:
    Value: !Ref BatchJobQueueEc2IntelOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueEc2IntelOnDemand
  BatchJobQueueEc2NvidiaOnDemand:
    Value: !Ref BatchJobQueueEc2NvidiaOnDemand
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobQueueEc2NvidiaOnDemand
