---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for Chatbot
Parameters:
  SystemName:
    Description: System Name.
    Type: String
    Default: iobatch
  EnvType:
    Description: Environment Type.
    Type: String
    Default: dev
  TopicName:
    Description: SNS Topic Name.
    Type: String
    Default: batch-topic
  SlackWorkspaceId:
    Description: Slack Workspace ID.
    Type: String
  SlackChannelId:
    Description: Slack Channel ID.
    Type: String
Resources:
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${SystemName}-${EnvType}-${TopicName}
  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SnsTopic
      Topics:
        - !Ref SnsTopic
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${SystemName}-${EnvType}-${TopicName}-event-rule
      EventPattern:
        source:
          - aws.batch
      Targets:
        - Arn: !Ref SnsTopic
          Id: sns-topic
  ChatbotConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub ${SystemName}-${EnvType}-${TopicName}-chatbot-config
      IamRoleArn: arn:aws:iam::955526594440:role/aws-service-role/management.chatbot.amazonaws.com/AWSServiceRoleForAWSChatbot
      LoggingLevel: NONE
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SnsTopicArns:
        - !Ref SnsTopic
Outputs:
  SnsTopic:
    Value: !Ref SnsTopic
    Export:
      Name: !Sub ${AWS::StackName}-SnsTopic
  SnsTopicPolicy:
    Value: !Ref SnsTopicPolicy
    Export:
      Name: !Sub ${AWS::StackName}-SnsTopicPolicy
  EventRule:
    Value: !Ref EventRule
    Export:
      Name: !Sub ${AWS::StackName}-EventRule
  ChatbotConfiguration:
    Value: !Ref ChatbotConfiguration
    Export:
      Name: !Sub ${AWS::StackName}-ChatbotConfiguration
