---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for Chatbot
Parameters:
  SystemName:
    Description: System Name.
    Type: String
    Default: iobatch
  EnvType:
    Description: Environment Type.
    Type: String
    Default: prd
  SlackWorkspaceId:
    Description: Slack Workspace ID.
    Type: String
    Default: XXXXXXXXX
  BatchSlackChannelId:
    Description: Slack Channel ID for AWS Batch.
    Type: String
    Default: awsbatch
  StepFunctionsSlackChannelId:
    Description: Slack Channel ID for AWS Step Functions.
    Type: String
    Default: awsstepfunctions
Resources:
  BatchSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${SystemName}-${EnvType}-batch-topic
  BatchSnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref BatchSnsTopic
      Topics:
        - !Ref BatchSnsTopic
  BatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${SystemName}-${EnvType}-batch-topic-event-rule
      EventPattern:
        source:
          - aws.batch
      Targets:
        - Arn: !Ref BatchSnsTopic
          Id: batch-sns-topic
  BatchChatbotConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub ${SystemName}-${EnvType}-batch-topic-chatbot-config
      IamRoleArn: arn:aws:iam::955526594440:role/aws-service-role/management.chatbot.amazonaws.com/AWSServiceRoleForAWSChatbot
      LoggingLevel: NONE
      SlackChannelId: !Ref BatchSlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SnsTopicArns:
        - !Ref BatchSnsTopic
  StepFunctionsSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${SystemName}-${EnvType}-stepfunctions-topic
  StepFunctionsSnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref StepFunctionsSnsTopic
      Topics:
        - !Ref StepFunctionsSnsTopic
  StepFunctionsEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${SystemName}-${EnvType}-stepfunctions-topic-event-rule
      EventPattern:
        source:
          - aws.states
      Targets:
        - Arn: !Ref StepFunctionsSnsTopic
          Id: stepfunctions-sns-topic
  StepFunctionsChatbotConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub ${SystemName}-${EnvType}-stepfunctions-topic-chatbot-config
      IamRoleArn: arn:aws:iam::955526594440:role/aws-service-role/management.chatbot.amazonaws.com/AWSServiceRoleForAWSChatbot
      LoggingLevel: NONE
      SlackChannelId: !Ref StepFunctionsSlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SnsTopicArns:
        - !Ref StepFunctionsSnsTopic
