---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for IAM
Parameters:
  SystemName:
    Description: System Name.
    Type: String
    Default: iobatch
  EnvType:
    Description: Environment Type.
    Type: String
    Default: dev
  S3StackName:
    Description: S3 Stack Name.
    Type: String
    Default: iobatch-dev-s3
Resources:
  # IAM User Groups
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: administrator-group
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  EcrUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ecr-user-group
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
  OpsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${SystemName}-${EnvType}-operator-group
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      Policies:
        - PolicyName: !Sub ${SystemName}-${EnvType}-operator-batch-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: '*'
                Effect: Allow
                Action:
                  - batch:Describe*
                  - batch:List*
                  - batch:SubmitJob
                  - batch:CancelJob
                  - batch:TerminateJob
              - Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/*${SystemName}*
                Effect: Allow
                Action:
                  - iam:PassRole
        - PolicyName: !Sub ${SystemName}-${EnvType}-operator-s3-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: '*'
                Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetAccountPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketPolicyStatus
                  - s3:GetBucketAcl
                  - s3:ListAccessPoints
              - Resource: !Sub arn:aws:s3:::${SystemName}-${EnvType}*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
              - Resource: !Sub arn:aws:s3:::${SystemName}-${EnvType}*/*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:*Object*
                  - s3:*MultipartUpload*
  DevGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${SystemName}-${EnvType}-developer-group
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: !Sub ${SystemName}-${EnvType}-developer-batch-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: '*'
                Effect: Allow
                Action:
                  - batch:Describe*
                  - batch:List*
                  - batch:RegisterJobDefinition
                  - batch:DeregisterJobDefinition
              - Resource: '*'
                Effect: Allow
                Action:
                  - iam:PassRole
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - ecs-tasks.amazonaws.com
  # IAM Roles
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - batch.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchJobRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${SystemName}-${EnvType}-BatchJobRole-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-InputBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-ReferenceBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-OutputBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:PutObject
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-ArchiveBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:PutObject
  BatchJobExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchJobExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchInstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: BatchInstanceRole
Outputs:
  BatchServiceRole:
    Value: !GetAtt BatchServiceRole.Arn
    Description: BatchServiceRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchServiceRole
  BatchJobRole:
    Value: !GetAtt BatchJobRole.Arn
    Description: BatchJobRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobRole
  BatchJobExecutionRole:
    Value: !GetAtt BatchJobExecutionRole.Arn
    Description: BatchJobExecutionRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobExecutionRole
  BatchInstanceRole:
    Value: !GetAtt BatchInstanceRole.Arn
    Description: BatchInstanceRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchInstanceRole
  BatchInstanceProfile:
    Value: !GetAtt BatchInstanceProfile.Arn
    Description: BatchInstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-BatchInstanceProfile
