---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for GuardDuty
Parameters:
  SnsTopicName:
    Description: SNS Topic Name.
    Type: String
    Default: guardduty-finding-topic
Resources:
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${SnsTopicName}-topic
  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: default_policy_ID
        Version: 2012-10-17
        Statement:
          - Sid: default_statement_ID
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
              - SNS:Receive
            Resource: !Ref SnsTopic
            Condition:
              StringEquals:
                'AWS:SourceOwner': !Ref AWS::AccountId
          - Sid: AWSEvents_AlertGuardDutyFindings_Id123
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SnsTopic
      Topics:
        - !Ref SnsTopic
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${SnsTopicName}-rule
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      Targets:
        - Arn: !Ref SnsTopic
          Id: Id123
